In [295]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.font_manager
from sklearn.model_selection import train_test_split

In [316]:
data=pd.read_csv('D:\ms\s3-pattern\Project2Data.txt', encoding='utf-8-sig', sep='\s*,\s*', engine='python')
data.head()
df_train = data

In [317]:
#df_train, df_test = train_test_split(data,  test_size=0.3)


In [318]:
df_train.reset_index()

index  foggy   no
0        0  foggy   no
1        1  foggy   no
2        2  rainy  yes
3        3  sunny   no
4        4  foggy   no
..     ...    ...  ...
994    994  sunny   no
995    995  foggy   no
996    996  rainy  yes
997    997  foggy  yes
998    998  sunny   no

[999 rows x 3 columns]

In [319]:
 df_train.columns = ['state','obs']

In [320]:
states = df_train.state.unique()
emissions = df_train.obs.unique()
states
states=['sunny','rainy','foggy']
print(emissions)
emissions =['no','yes']

['no' 'yes']


In [321]:
intial_state_prob = [1,0,0]
N = len(states)
M = len(emissions)

In [322]:
res = [ [ 0 for i in range(N) ] for j in range(N) ] 
res = pd.DataFrame(res)
type(res)
res.columns=states
res.index = states 

ems = [ [ 0 for i in range(N) ] for j in range(M) ] 
ems = pd.DataFrame(ems)
ems.columns=states
ems.index = emissions 

In [323]:
print(res)
res.iloc[0][1]
print(ems)

       sunny  rainy  foggy
sunny      0      0      0
rainy      0      0      0
foggy      0      0      0
     sunny  rainy  foggy
no       0      0      0
yes      0      0      0


In [324]:
def count_emssion_matrix( df_train):
    #res = pd.DataFrame(index=states, columns=states)
    for i in range(len(df_train)-1):
        #print(df_train.iloc[i]['state'],df_train.iloc[i+1]['state'])
        if(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i]['obs'] == 'yes'):
           ems.iloc[0][0] = res.iloc[0][0]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i]['obs'] == 'no'):
           ems.iloc[1][0] = res.iloc[1][0] +1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i]['obs'] == 'yes'):
           ems.iloc[0][1]  = res.iloc[0][1]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i]['obs'] == 'no'):
          ems.iloc[1][1] = res.iloc[1][1]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i]['obs'] == 'yes'):
           ems.iloc[0][2] = res.iloc[1][1]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i]['obs'] == 'no'):
           ems.iloc[1][2] = res.iloc[2][1]+1
    #print(ems)  
    return ems

In [325]:
def countmatrix( df_train):
    #res = pd.DataFrame(index=states, columns=states)
    #res = pd.DataFrame(index=states, columns=states)
    for i in range(len(df_train)-1):
        #print(df_train.iloc[i]['state'],df_train.iloc[i+1]['state'])
        if(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'sunny'):
           res.iloc[0][0] = res.iloc[0][0]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'sunny'):
           res.iloc[1][0] = res.iloc[1][0] +1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'sunny'):
           res.iloc[2][0]  = res.iloc[2][0]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'rainy'):
          res.iloc[0][1] = res.iloc[0][1]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'rainy'):
           res.iloc[1][1] = res.iloc[1][1]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'rainy'):
           res.iloc[2][1] = res.iloc[2][1]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'foggy'):
           res.iloc[0][2] = res.iloc[0][2]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'foggy'):
           res.iloc[1][2] = res.iloc[1][2]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'foggy'):
           res.iloc[2][2] = res.iloc[2][2]+1
    return res

In [326]:
#trans_prob = count
def emissionmatrix(df_train):
    colsum = []
    count_ems = pd.DataFrame(index=emissions, columns=states)
    ems1 = np.zeros((len(emissions),len(states)))
    #print(ems1.shape)
    for i in range(len(df_train)-1):
        #print(df_train.iloc[i]['state'],df_train.iloc[i+1]['state'])
        if(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i]['obs'] == 'no'):
           ems1[0][0] = ems1[0][0]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i]['obs'] == 'yes'):
           ems1[1][0] = ems1[1][0] +1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i]['obs'] == 'no'):
           ems1[0][1]  = ems1[0][1]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i]['obs'] == 'yes'):
           ems1[1][1] = ems1[1][1]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i]['obs'] == 'no'):
           ems1[0][2] = ems1[0][2]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i]['obs'] == 'yes'):
           ems1[1][2] = ems1[1][2]+1
    #print(ems1)  
    #count_ems = count_emssion_matrix(df_train)
    #print(count_ems)
    count_ems = ems1
    d_ems = np.zeros((len(emissions),len(states)))
    
    for i in range(len(count_ems[1])):
        colsum= count_ems.sum(axis=0)
    #print(count_ems)
    #print(len(count_ems.iloc[0],len(count_ems))
    for i in range (len(count_ems)): 
        for p in range(len(count_ems[0])):        
             temp = count_ems[i][p]/colsum[p]
# #            trans_prob.set_value(i, p, temp)
             d_ems[i,p] = temp
# #            print(i,p)
# #      
    #print(d_ems)
    #type(trans_prob)
    return d_ems

In [327]:
#trans_prob = count
def transitionmatrix(df_train):
    rowsum = []
    count = pd.DataFrame(index=states, columns=states)
    res1 = np.zeros((len(states),len(states)))
    for i in range(len(df_train)-1):
        #print(df_train.iloc[i]['state'],df_train.iloc[i+1]['state'])
        if(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'sunny'):
           res1[0][0] = res1[0][0]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'sunny'):
           res1[1][0] = res1[1][0] +1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'sunny'):
           res1[2][0]  = res1[2][0]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'rainy'):
          res1[0][1] = res1[0][1]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'rainy'):
           res1[1][1] = res1[1][1]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'rainy'):
           res1[2][1] = res1[2][1]+1
        elif(df_train.iloc[i]['state'] == 'sunny' and df_train.iloc[i+1]['state'] == 'foggy'):
           res1[0][2] = res1[0][2]+1
        elif(df_train.iloc[i]['state'] == 'rainy' and df_train.iloc[i+1]['state'] == 'foggy'):
           res1[1][2] = res1[1][2]+1
        elif(df_train.iloc[i]['state'] == 'foggy' and df_train.iloc[i+1]['state'] == 'foggy'):
           res1[2][2] = res1[2][2]+1
    count = pd.DataFrame(res1, columns=states, index=states)
    #print(res1)
    d = np.zeros((len(states),len(states)))
    
    for i in range(len(count)):
        rowsum = count.sum(axis=1)
    for i in range(len(count)): 
        for p in range(len(count.iloc[i])):        
           temp = count.iloc[i][p]/rowsum[i]
           #trans_prob.set_value(i, p, temp)
           d[i,p] = temp
           #print(temp)
     
    #print(trans_prob)
    #type(trans_prob)
    return d

In [328]:

chakka = transitionmatrix(df_train)
chakka1 = chakka
transitionprobality = pd.DataFrame(chakka1, columns=states, index=states)
print(transitionprobality)
ems_temp = emissionmatrix(df_train)
emissionprobability =  pd.DataFrame(ems_temp, columns=states, index=emissions)
print(emissionprobability)

          sunny     rainy     foggy
sunny  0.795132  0.054767  0.150101
rainy  0.195918  0.579592  0.224490
foggy  0.207692  0.292308  0.500000
        sunny     rainy     foggy
no   0.914807  0.187755  0.696154
yes  0.085193  0.812245  0.303846


In [331]:
df_test = df_test.replace(to_replace=['no', 'yes'], value=[0, 1])
df_test.columns = ['state','obs']
#V = df_test['obs'].values
#V = df_test['obs'].values
ip_obs1 = np.array(('no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes'))
ip_obs = np.where(V1 == 'yes', 1, 0)
print(type(V))
a = chakka1
b = ems_temp.transpose()

initial_distribution = np.array((1,0,0))
alpha = np.zeros((ip_obs.shape[0], a.shape[0]))
alpha[0, :] = initial_distribution * b[:, ip_obs[0]]
#print(alpha.shape) 
for t in range(1, ip_obs.shape[0]):
        for j in range(a.shape[0]):
           
            alpha[t, j] = alpha[t - 1].dot(a[:, j]) * b[j, ip_obs[t]]
alpha_tranpose = alpha.transpose()
print(alpha_tranpose)


<class 'numpy.ndarray'>
[[9.14807302e-01 6.65423896e-01 5.03872492e-01 3.61959330e-02
  4.34356526e-02 3.80217861e-02 2.88517070e-03 3.78484165e-04
  1.25786457e-03 1.13778203e-04]
 [0.00000000e+00 9.40671995e-03 1.31123106e-02 5.33449023e-02
  8.35700356e-03 2.77989303e-03 6.53177934e-03 4.19660034e-03
  5.27127333e-04 5.69435057e-04]
 [0.00000000e+00 9.55915822e-02 1.04275893e-01 3.97167951e-02
  2.59434573e-02 1.48750978e-02 4.18357584e-03 1.21270285e-03
  1.11750541e-03 2.63098765e-04]]


In [342]:
T = ip_obs.shape[0]
M = a.shape[0]
omega = np.zeros((T, M))
omega[0, :] = np.log(initial_distribution * b[:, ip_obs[0]])
prev = np.zeros((T - 1, M))
for t in range(1, T):
        for j in range(M):
            # Same as Forward Probability
            probability = omega[t - 1] + np.log(a[:, j]) + np.log(b[j, V[t]])
            #print(probability)
            # This is our most probable state given previous state at time t (1)
            prev[t - 1, j] = np.argmax(probability)
            #print(np.argmax(probability))
            # This is the probability of the most probable state (2)
            omega[t, j] = np.max(probability)
# Path Array
S = np.zeros(T)
 
# Find the most probable last hidden state
last_state = np.argmax(omega[T - 1, :])
 
S[0] = last_state
print(prev)
backtrack_index = 1
for i in range(T - 2, -1, -1):
        S[backtrack_index] = prev[i, int(last_state)]
        last_state = prev[i, int(last_state)]
        backtrack_index += 1
print(S) 
 # Flip the path array since we were backtracking
S = np.flip(S, axis=0)
# Convert numeric values to actual hidden states
result = []
for s in S:
        if s == 0:
            result.append("sunny")
        elif s== 1:
            result.append("rainy")
        else:
            result.append("foggy")
print(result)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 2.]
 [0. 0. 0.]
 [0. 1. 2.]
 [1. 1. 1.]
 [0. 1. 2.]]
[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
['sunny', 'sunny', 'sunny', 'sunny', 'sunny', 'sunny', 'rainy', 'rainy', 'rainy', 'rainy']


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [330]:
inputstates=['sunny','sunny','foggy','rainy']

In [201]:
alphacols = len(inputstates)
alphaRows = len(states)

In [202]:
alpha = [[0]*(alphacols+1)]*alphaRows
print(alpha)
#alpha_frwadalgo(alpha,inputstates,transitionprobality,emissionprobability)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [205]:

ipstates_timeorder = ['zeroTh_time','sunny','sunny','rainy','foggy']

alpha_new = np.zeros((len(states), len(ipstates_timeorder)))
alpha_new[:,0] = intial_state_prob

print(alpha_new)
print(transitionprobality)
#print(emissionprobability)
for i in range(len(alpha_new)):
    for j in range(1, len(alpha_new[0][:])):  
                alp_prev = alpha_new[:,j-1]
                cilname = ipstates_timeorder[j]
                trans = transitionprobality.iloc[:][cilname]
                a_val = alp_prev.dot(trans)
                to_ip_state = ipstates_timeorder[j]
                from_obs = emissions[i]
                
                #print(alp_prev)
                #print(trans)
                #print(a_val)
                print(emissionprobability.iloc[from_obs][to_ip_state])
                #sum = 0;
#                 for x in range(0, len(alpha_new)-1):
#                     sum+=alpha_new.iloc[x][j-1]*trans.iloc[x][j]
#                 #temp = sum * emiss[i][j]
#                 alpha_new.iloc[i][j] = sum

return alpha_new

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
          sunny     rainy     foggy
sunny  0.535817  0.200573  0.263610
rainy  0.460606  0.266667  0.272727
foggy  0.461957  0.277174  0.260870


TypeError: Cannot index by location index with a non-integer key